postgresql:
  enabled: true
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: "app_user"
    database: "auth_db"
  primary:
    initdb:
      scripts:
        01-create-databases.sql: |
          CREATE DATABASE artists_db;
          CREATE DATABASE appointments_db;
          CREATE DATABASE notification_db;
          CREATE DATABASE cronjobs_db;
          GRANT ALL PRIVILEGES ON DATABASE artists_db TO "app_user";
          GRANT ALL PRIVILEGES ON DATABASE appointments_db TO "app_user";
          GRANT ALL PRIVILEGES ON DATABASE notification_db TO "app_user";
          GRANT ALL PRIVILEGES ON DATABASE cronjobs_db TO "app_user";
    persistence:
      enabled: true
      size: 1Gi

rabbitmq:
  enabled: true
  image:
    repository: bitnamilegacy/rabbitmq
  auth:
    username: "app_user"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
# controla si este chart crea su propio Secret de la app
# en P8 esto se desactiva porque el Secret real lo crea un SealedSecret
# aplicado por ArgoCD desde el repositorio GitOps
secrets:
  manageInChart: true

# cronjobs: insert-execution (cada 2 min) es el generador de datos para medir el RPO en P9
cronjobs:
  enabled: true
  image: ghcr.io/aidaorantes9/sa-practica-cronjobs:1.0.0
