postgresql:
  auth:
    postgresPassword: "PostgresAdmin2026Segura"
    password: "AppUserPassword2026"

rabbitmq:
  auth:
    password: "RabbitMQPassword2026"

secrets:
  jwtSecret: "cambia_este_secreto_en_produccion"
  aesSecretKey: "12345678901234567890123456789012"
  hmacSecretKey: "otro_secreto_para_el_hash_del_correo"