{{- if .Values.podDisruptionBudget.enabled }}
# garantiza que el drenaje de un nodo nunca deje al servicio sin replicas disponibles
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "artists-service.fullname" . }}
  labels:
    {{- include "artists-service.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "artists-service.selectorLabels" . | nindent 6 }}
{{- end }}
