apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | required "falta postgresql.auth.password" | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | required "falta secrets.jwtSecret" | quote }}
  AES_SECRET_KEY: {{ .Values.secrets.aesSecretKey | required "falta secrets.aesSecretKey" | quote }}
  HMAC_SECRET_KEY: {{ .Values.secrets.hmacSecretKey | required "falta secrets.hmacSecretKey" | quote }}
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | required "falta rabbitmq.auth.password" | quote }}